name: text_scroll
description: TextScroll Flutter widget adds text auto-scrolling functionality (marquee text).
version: 0.2.1
repository: https://github.com/yurii-khi/text_scroll

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
